### ISSUE TITLE
Generate clients for each of the examples as part of release

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/examples#140]
**Is your feature request related to a problem? Please describe.**
Having the examples is great, but having code to try the examples out would be even better!

Im not certain that this would belong here and not generator-client...

The idea is to have npm/cargo installable clients for the examples

**Comment by devonwesley** [comment]
I was going to work on generating and creating releases for clients.

I can look into creating like a "strategy" module, that does the deployment for each client.

**Comment by shanejonas** [comment]
I think for this particular repo, `semantic-release` has a `publish` step, heres an example of what we do for `spec`: https://github.com/open-rpc/spec/blob/master/.releaserc

we already have the `.releaserc` in this repo, its just what do we want to do on release might change.
