### ISSUE TITLE
method naming conventions

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/examples#169]
**Is your feature request related to a problem? Please describe.**
As a developer, i'd like clear naming conventions to remove unnecessary variation.

I've also outlined my thoughts around how this naming and it being a foundational layer to get a RESTful style interface with JSON-RPC [here](https://github.com/open-rpc/open-rpc/issues/30).

#### gRPC's naming conventions:
https://cloud.google.com/apis/design/naming_convention#method_names

> Carefully consider use of names that may conflict with keywords in common programming languages. Such names may be used but will likely trigger additional scrutiny during API review. Use them judiciously and sparingly.

`VerbNoun`
> The verb portion of the method name should use the [imperative mood](https://en.wikipedia.org/wiki/Imperative_mood#English), which is for orders or commands rather than the indicative mood which is for questions.

**Comment by shanejonas** [comment]
> From the article [here](https://github.com/open-rpc/open-rpc/issues/30).


## Path to API Enlightenment - REST over JSON-RPC

Based on [Richardson Maturity Model](https://martinfowler.com/articles/richardsonMaturityModel.html) description of the different layers of REST APIs. But applied with OpenRPC in mind:

- Level 0 - Basic transport agnostic JSON-RPC API

- Level 1 - Break down complexity into multiple resources or services.

- Level 2 - Use a [standard set of verbs and nouns](https://cloud.google.com/apis/design/naming_convention#method_names) removing unnecessary variation.

- Level 3 - Introduce [service discovery](https://spec.open-rpc.org/#service-discovery-method) and [links](https://spec.open-rpc.org/#link-object) via the OpenRPC interface definition, -providing a self-documenting protocol.

**Comment by shanejonas** [comment]
More resource on naming with `actionResource` in [the art of naming variables](https://hackernoon.com/the-art-of-naming-variables-52f44de00aad)

**Comment by BelfordZ** [comment]
@shanejonas is there something still to be done here?

**Comment by shanejonas** [comment]
would be great to follow the naming conventions outlined here
